<?php

/**
 * @file
 * Subscriptions module installation.
 */

/**
 * Implements hook_schema().
 *
 * @return array
 */
function subscriptions_schema() {

  $schema['subscriptions'] = array(
    'fields' => array(
      'sid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'module' => array(
        'type' => 'varchar',
        'length' => '64',
        'not null' => FALSE,
      ),
      'field' => array(
        'type' => 'varchar',
        'length' => '32',
        'not null' => FALSE,
      ),
      'value' => array(
        'type' => 'varchar',
        'length' => '237',
        'not null' => FALSE,
      ),
      'recipient_uid' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'send_interval' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'author_uid' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'send_updates' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
      'send_comments' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('sid'),
    'indexes' => array(
      'module' => array('module', 'field', 'value'),
      'recipient_uid' => array('recipient_uid'),
    ),
  );


  $schema['subscriptions_queue'] = array(
    'fields' => array(
      'sqid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'uid' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'name' => array(
        'type' => 'varchar',
        'length' => '60',
        'not null' => FALSE,
      ),
      'language' => array(
        'type' => 'varchar',
        'length' => '12',
        'not null' => FALSE,
      ),
      'module' => array(
        'type' => 'varchar',
        'length' => '64',
        'not null' => FALSE,
      ),
      'field' => array(
        'type' => 'varchar',
        'length' => '32',
        'not null' => FALSE,
      ),
      'value' => array(
        'type' => 'varchar',
        'length' => '237',
        'not null' => FALSE,
      ),
      'author_uid' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'send_interval' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
      'digest' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => FALSE,
      ),
      'load_args' => array(
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
      ),
      'load_function' => array(
        'type' => 'varchar',
        'length' => '60',
        'not null' => TRUE,
        'default' => '',
      ),
      'is_new' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => FALSE,
      ),
      'last_sent' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'suspended' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('sqid'),
    'indexes' => array(
      'load_args' => array('load_args', 'load_function', 'uid'),
      'uid' => array('uid'),
    ),
  );


  $schema['subscriptions_user'] = array(
    'fields' => array(
      'uid' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'digest' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'secure_links' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'send_interval' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => -1,
      ),
      'send_updates' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'send_comments' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'send_interval_visible' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => -1,
      ),
      'send_updates_visible' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'send_comments_visible' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'autosub_on_post' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'autosub_on_update' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'autosub_on_comment' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'send_self' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => -1,
      ),
      'suspended' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('uid'),
  );


  $schema['subscriptions_last_sent'] = array(
    'fields' => array(
      'uid' => array(
        'type' => 'int',
        'not null' => TRUE,
      ),
      'send_interval' => array(
        'type' => 'int',
        'not null' => TRUE,
      ),
      'last_sent' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('uid', 'send_interval'),
  );

  return $schema;
}

/**
 * Implements hook_install().
 */
function subscriptions_install() {
  // Remove old cruft if it's still around.
  if (db_table_exists('subscriptions_mail_edit')) {
    db_drop_table('subscriptions_mail_edit'); // old table from 5.x-2.x
  }
  if (db_table_exists('subscriptions_old')) {
    db_drop_table('subscriptions_old'); // old backup from 5.x-1.x
  }
  if (db_table_exists('subscriptions_holding')) {
    db_drop_table('subscriptions_holding'); // old left-over from 5.x-1.x
  }
  if (db_table_exists('subscriptions_holding_old')) {
    db_drop_table('subscriptions_holding_old'); // old backup from 5.x-1.x
  }
  if (db_table_exists('subscriptions_sent')) { // old left-over from first
    db_drop_table('subscriptions_sent'); // incarnation of 5.x-2.0
  }

  // Create initial data.
  db_insert('subscriptions_user')
    ->fields(array(
    'uid' => -BACKDROP_AUTHENTICATED_RID,
    'digest' => 0,
    'secure_links' => 0,
    'send_interval' => 1,
    'send_updates' => 1,
    'send_comments' => 1,
    'send_interval_visible' => 0,
    'send_updates_visible' => 0,
    'send_comments_visible' => 0,
    'autosub_on_post' => 0,
    'autosub_on_update' => 0,
    'autosub_on_comment' => 0,
    'send_self' => 1,
  ))
    ->execute();
  $select = db_select('users', 'u')
    ->fields('u', array('uid'))
    ->condition('u.uid', 0, '>');
  db_insert('subscriptions_user')
    ->from($select)
    ->execute();
  // Dynamically generated variable data was detected on the following lines.
  // /subscriptions/subscriptions.admin.inc line 1094
  // /subscriptions/subscriptions_content.module line 475
  // /subscriptions/subscriptions_content.module line 804
}

/**
 * Implements hook_uninstall().
 */
function subscriptions_uninstall() {
  if (db_table_exists('mail_edit')) {
    db_delete('mail_edit')
      ->condition('id', 'subscriptions_%', 'LIKE')
      ->execute();
  }
  if (db_table_exists('mail_edit_registry')) {
    db_delete('mail_edit_registry')
      ->condition('id', 'subscriptions_%', 'LIKE')
      ->execute();
  }

  config_clear('subscriptions.settings', 'subscriptions_avoid_empty_subscribe_links');
  config_clear('subscriptions.settings', 'subscriptions_blocked_content_types');
  config_clear('subscriptions.settings', 'subscriptions_blocked_nodes');
  config_clear('subscriptions.settings', 'subscriptions_cron_percent');
  config_clear('subscriptions.settings', 'subscriptions_form_expanded');
  config_clear('subscriptions.settings', 'subscriptions_form_in_block');
  config_clear('subscriptions.settings', 'subscriptions_form_link_only');
  config_clear('subscriptions.settings', 'subscriptions_generate_full_node');
  config_clear('subscriptions.settings', 'subscriptions_hide_overview_page');
  config_clear('subscriptions.settings', 'subscriptions_link_teaser');
  config_clear('subscriptions.settings', 'subscriptions_omitted_taxa');
  config_clear('subscriptions.settings', 'subscriptions_restricted_taxa');
  config_clear('subscriptions.settings', 'subscriptions_send_intervals');
  config_clear('subscriptions.settings', 'subscriptions_show_by_author_options');
  config_clear('subscriptions.settings', 'subscriptions_static_content_types');
  config_clear('subscriptions.settings', 'subscriptions_unlisted_content_types');

  // also remove legacy 5.x-1.9(-dev) variables:
  config_clear('subscriptions.settings', 'subscriptions_allow_vid');
  config_clear('subscriptions.settings', 'subscriptions_autoset');
  config_clear('subscriptions.settings', 'subscriptions_email_body');
  config_clear('subscriptions.settings', 'subscriptions_email_subject');
  config_clear('subscriptions.settings', 'subscriptions_sendself');
  config_clear('subscriptions.settings', 'subscriptions_teaser');
  config_clear('subscriptions.settings', 'subscriptions_testpost');
  config_clear('subscriptions.settings', 'subscriptions_usecron');
  config_clear('subscriptions.settings', 'subscriptions_usersmenu');
}

/**
 * Migrate subscriptions variables to config.
 */
function subscriptions_update_1000() {
  $config = config('subscriptions.settings');
  $config->set('subscriptions_show_install_info', update_variable_get('subscriptions_show_install_info', '1'));
  $config->set('subscriptions_hide_overview_page', update_variable_get('subscriptions_hide_overview_page', '0'));
  $config->set('subscriptions_send_intervals', update_variable_get('subscriptions_send_intervals', 'dynamic value in file /subscriptions/subscriptions.admin.inc line 1094'));
  $config->set('subscriptions_blocked_nodes', update_variable_get('subscriptions_blocked_nodes', ''));
  $config->set('subscriptions_unlisted_content_types', update_variable_get('subscriptions_unlisted_content_types', array()));
  $config->set('subscriptions_blocked_content_types', update_variable_get('subscriptions_blocked_content_types', array()));
  $config->set('subscriptions_static_content_types', update_variable_get('subscriptions_static_content_types', array()));
  $config->set('subscriptions_avoid_empty_subscribe_links', update_variable_get('subscriptions_avoid_empty_subscribe_links', '0'));
  $config->set('subscriptions_default_workflow_content_type', update_variable_get('subscriptions_default_workflow_content_type', 'dynamic variable in file /subscriptions/subscriptions_content.module line 475'));
  $config->set('subscriptions_key_content_types', update_variable_get('subscriptions_key_content_types', 'dynamic variable in file /subscriptions/subscriptions_content.module line 804'));
  $config->set('subscriptions_watchall', update_variable_get('subscriptions_watchall', '0'));
  $config->set('subscriptions_mail_trash_silently', update_variable_get('subscriptions_mail_trash_silently', '0'));
  $config->set('subscriptions_site_mail_name', update_variable_get('subscriptions_site_mail_name', array()));
  $config->set('subscriptions_number_of_mails', update_variable_get('subscriptions_number_of_mails', '0'));
  $config->set('subscriptions_watchstats', update_variable_get('subscriptions_watchstats', '1'));
  $config->set('subscriptions_watchgood', update_variable_get('subscriptions_watchgood', '1'));
  $config->set('subscriptions_showmailkeys', update_variable_get('subscriptions_showmailkeys', array()));
  $config->set('subscriptions_mail_unaccessed_users', update_variable_get('subscriptions_mail_unaccessed_users', array()));
  $config->set('subscriptions_preview_mode', update_variable_get('subscriptions_preview_mode', 'text'));
  $config->set('subscriptions_site_mail', update_variable_get('subscriptions_site_mail', ''));
  $config->set('subscriptions_cron_percent', update_variable_get('subscriptions_cron_percent', '50'));
  $config->set('subscriptions_restricted_taxa', update_variable_get('subscriptions_restricted_taxa', array()));
  $config->set('subscriptions_omitted_taxa', update_variable_get('subscriptions_omitted_taxa', array()));
  $config->set('subscriptions_form_in_block', update_variable_get('subscriptions_form_in_block', '0'));
  $config->set('subscriptions_form_link_only', update_variable_get('subscriptions_form_link_only', '0'));
  $config->set('subscriptions_form_expanded', update_variable_get('subscriptions_form_expanded', '0'));
  $config->set('subscriptions_show_by_author_options', update_variable_get('subscriptions_show_by_author_options', '1'));
  $config->save();

  update_variable_del('subscriptions_show_install_info');
  update_variable_del('subscriptions_hide_overview_page');
  update_variable_del('subscriptions_send_intervals');
  update_variable_del('subscriptions_blocked_nodes');
  update_variable_del('subscriptions_unlisted_content_types');
  update_variable_del('subscriptions_blocked_content_types');
  update_variable_del('subscriptions_static_content_types');
  update_variable_del('subscriptions_avoid_empty_subscribe_links');
  update_variable_del('subscriptions_default_workflow_content_type');
  update_variable_del('subscriptions_key_content_types');
  update_variable_del('subscriptions_watchall');
  update_variable_del('subscriptions_mail_trash_silently');
  update_variable_del('subscriptions_site_mail_name');
  update_variable_del('subscriptions_number_of_mails');
  update_variable_del('subscriptions_watchstats');
  update_variable_del('subscriptions_watchgood');
  update_variable_del('subscriptions_showmailkeys');
  update_variable_del('subscriptions_mail_unaccessed_users');
  update_variable_del('subscriptions_preview_mode');
  update_variable_del('subscriptions_site_mail');
  update_variable_del('subscriptions_cron_percent');
  update_variable_del('subscriptions_restricted_taxa');
  update_variable_del('subscriptions_omitted_taxa');
  update_variable_del('subscriptions_form_in_block');
  update_variable_del('subscriptions_form_link_only');
  update_variable_del('subscriptions_form_expanded');
  update_variable_del('subscriptions_show_by_author_options');
}

