<?php

/**
 * @file
 * Organic Groups Subscriptions module installation.
 */

/**
 * Implements hook_disable().
 */
function subscriptions_og_disable() {
  // Removes our queue items.
  db_delete('subscriptions_queue')
    ->condition('module', 'node')
    ->condition('field', 'group_audience')
    ->execute();
}

/**
 * Implements hook_uninstall().
 */
function subscriptions_og_uninstall() {
  config_clear('subscriptions_og.settings', 'subscriptions_og_autosubscribe');
}

/**
 * Migrate subscriptions_og variables to config.
 */
function subscriptions_og_update_1000() {
  $config = config('subscriptions_og.settings');
  $config->set('subscriptions_og_autosubscribe', update_variable_get('subscriptions_og_autosubscribe', array()));
  $config->save();

  update_variable_del('subscriptions_og_autosubscribe');
}

/**
 * Implements hook_install().
 */
function subscriptions_og_install() {
  // Dynamically generated variable data was detected.
}
